// Generated by https://quicktype.io

export interface PodcastsPopulars {
   data: PodcastPopular[];
   total: number;
}

export interface PodcastPopular {
   id: number;
   title: string;
   description: string;
   available: boolean;
   fans: number;
   link: string;
   share: string;
   picture: string;
   picture_small: string;
   picture_medium: string;
   picture_big: string;
   picture_xl: string;
   type: Type;
}

export enum Type {
   Podcast = 'podcast',
}
