// Generated by https://quicktype.io

export interface ArtistsNavbar {
   data: ArtistNavbar[];
   total: number;
   next: string;
}

export interface ArtistNavbar {
   id: number;
   name: string;
   link: string;
   picture: string;
   picture_small: string;
   picture_medium: string;
   picture_big: string;
   picture_xl: string;
   nb_album: number;
   nb_fan: number;
   radio: boolean;
   tracklist: string;
   type: Type;
}

export enum Type {
   Artist = 'artist',
}
