// Generated by https://quicktype.io

export interface Genres {
   data: Genre[];
   total: number;
}

export interface Genre {
   id: number;
   name: string;
   picture: string;
   picture_small: string;
   picture_medium: string;
   picture_big: string;
   picture_xl: string;
   type: Type;
}

export enum Type {
   Editorial = 'editorial',
}
